apiVersion:apps/v1
kind: Deployment
metadata:
  name: spring-example
  labels:
    app: spring-example
spec:
  selector:
    matchLabels:
        app: spring-example
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-example
    spec:
      containers:
        - name: spring-example
          image: docker.io/darojas/spring-example:latest
          ports:
            - containerPort: 8081
              protocol: TCP
          imagePullPolicy: Always