apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-example
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring-example
    spec:
      containers:
        - name: spring-example
          image: docker.io/darojas/spring-example:latest
          ports:
            - containerPort: 8081
              protocol: TCP
          imagePullPolicy: Always